# Generated by Django 5.1.3 on 2024-11-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_description', models.TextField()),
                ('solution', models.TextField()),
                ('error_image', models.ImageField(blank=True, null=True, upload_to='error_images/')),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='error_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning', models.TextField()),
                ('solution', models.TextField()),
                ('warning_image', models.ImageField(blank=True, null=True, upload_to='warning_images/')),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='warning_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='faq_images/')),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='faq_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
